### ISSUE TITLE
TensorFlow build issue

### ISSUE THREAD

**Issue by ViralBShah** [JuliaTPU/XLA.jl#3]
Building TensorFlow ──────→ `~/.julia/packages/TensorFlow/kl0uH/deps/build.log`
┌ Error: Error building `TensorFlow`:
│ [ Info: Building TensorFlow.jl for CPU use only. To enable the GPU, set the TF_USE_GPU environment variable to 1 and rebuild TensorFlow.jl
│ ERROR: LoadError: Python TensorFlow not installed
│ Please either:
│  - Rebuild PyCall to use Conda, by running in the julia REPL:
│     - `ENV["PYTHON"]=""; Pkg.build("PyCall"); Pkg.build("TensorFlow")`
│  - Or install the python binding yourself, eg by running pip
│     - `pip install tensorflow`
│     - then rebuilding TensorFlow.jl via `Pkg.build("TensorFlow")` in the julia REPL
│     - make sure you run the right pip, for the instance of python that PyCall is looking at.
│
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/viralbshah/.julia/packages/TensorFlow/kl0uH/deps/build.jl:48
│  [3] include at ./boot.jl:317 [inlined]
│  [4] include_relative(::Module, ::String) at ./loading.jl:1038
│  [5] include(::Module, ::String) at ./sysimg.jl:29
│  [6] include(::String) at ./client.jl:388
│  [7] top-level scope at none:0
│ in expression starting at /home/viralbshah/.julia/packages/TensorFlow/kl0uH/deps/build.jl:39
└ @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1069

**Comment by Keno** [comment]
Fixed by just deleting the python build steps from our TF.jl branch. We should still switch to grpc very soon, but this should work for now.
