### ISSUE TITLE
Include dumped_computation_to_text in tensorflow download

### ISSUE THREAD

**Issue by ViralBShah** [JuliaTPU/XLA.jl#4]

**Comment by Keno** [comment]
@staticfloat Can you do this for the next XRTServer bump? The executable in question is `//tensorflow/compiler/xla/tools:dumped_computation_to_text`.

**Comment by staticfloat** [comment]
Both `XRTServer_lite` and `XRTServer` now contain binaries with `dumped_computation_to_text` embedded within.

**Comment by Keno** [comment]
Do we need to bump the TF.jl version, or did you just replace the binaries?

**Comment by staticfloat** [comment]
We need to bump the TF.jl version to https://github.com/JuliaComputing/TensorFlow.jl/commit/b946edcda166838e33a787515e8d4062258205f6
